version: "3"
services:
  database:
    image: "postgres"
    volumes:
      - ./migration.sql:/docker-entrypoint-initdb.d/1-schema.sql
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=luciano_loja
    ports:
      - "5432:5432"
